name: Deploy Azure Function (Python v2)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Functions using Zip Deploy (remote build)
        uses: Azure/functions-action@v1
        with:
          app-name: "func-plc-dev-001"
          package: "."
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B1F462AC55CE4BE08A8A1DC7A595646D }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
